# Generated by Django 5.1.1 on 2024-09-08 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LeatherStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('price', models.IntegerField()),
                ('description', models.TextField(max_length=2000)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=4)),
                ('user_reviews', models.TextField(max_length=1000)),
            ],
        ),
    ]
