# Generated by Django 5.1.1 on 2024-09-16 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LeatherStore',
            new_name='Product',
        ),
    ]
