# Generated by Django 5.1.1 on 2024-09-16 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_leatherstore_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_ratings',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
