# Generated by Django 5.1.1 on 2024-09-16 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_product_user_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_ratings',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
