# Generated by Django 5.1.1 on 2024-09-16 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='user_ratings',
            field=models.IntegerField(),
        ),
    ]
