# Generated by Django 5.1.1 on 2024-09-29 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
    ]
